# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from typing import List
from PyQt6 import QtCore, QtGui, QtWidgets

from models import Employee, Smena
from datetime import datetime


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 628)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.mainWidget = QtWidgets.QWidget(parent=MainWindow)
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.mainWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.authPage = QtWidgets.QWidget()
        self.authPage.setObjectName("authPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.authPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.appBarAuthWidget = QtWidgets.QWidget(parent=self.authPage)
        self.appBarAuthWidget.setMaximumSize(QtCore.QSize(16777215, 112))
        self.appBarAuthWidget.setStyleSheet("background-color: rgb(118, 227, 131)")
        self.appBarAuthWidget.setObjectName("appBarAuthWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.appBarAuthWidget)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logoAuth = QtWidgets.QLabel(parent=self.appBarAuthWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoAuth.sizePolicy().hasHeightForWidth())
        self.logoAuth.setSizePolicy(sizePolicy)
        self.logoAuth.setMaximumSize(QtCore.QSize(77, 102))
        self.logoAuth.setText("")
        self.logoAuth.setPixmap(QtGui.QPixmap("logo.png"))
        self.logoAuth.setScaledContents(True)
        self.logoAuth.setObjectName("logoAuth")
        self.horizontalLayout_3.addWidget(self.logoAuth)
        self.labelAuthTitle = QtWidgets.QLabel(parent=self.appBarAuthWidget)
        self.labelAuthTitle.setMaximumSize(QtCore.QSize(16777215, 102))
        self.labelAuthTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelAuthTitle.setObjectName("labelAuthTitle")
        self.horizontalLayout_3.addWidget(self.labelAuthTitle)
        self.horizontalLayout_3.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_4.addWidget(self.appBarAuthWidget)
        self.widget = QtWidgets.QWidget(parent=self.authPage)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutAuth = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAuth.setObjectName("horizontalLayoutAuth")
        self.authWidget = QtWidgets.QWidget(parent=self.widget)
        self.authWidget.setMaximumSize(QtCore.QSize(300, 200))
        self.authWidget.setStyleSheet("background-color: rgb(118, 227, 131)#76e383")
        self.authWidget.setObjectName("authWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.authWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayoutForLoginRow = QtWidgets.QHBoxLayout()
        self.horizontalLayoutForLoginRow.setObjectName("horizontalLayoutForLoginRow")
        self.labelLogin = QtWidgets.QLabel(parent=self.authWidget)
        self.labelLogin.setObjectName("labelLogin")
        self.horizontalLayoutForLoginRow.addWidget(self.labelLogin)
        self.lineEditLogin = QtWidgets.QLineEdit(parent=self.authWidget)
        self.lineEditLogin.setStyleSheet("")
        self.lineEditLogin.setObjectName("lineEditLogin")
        self.horizontalLayoutForLoginRow.addWidget(self.lineEditLogin)
        self.verticalLayout_2.addLayout(self.horizontalLayoutForLoginRow)
        self.horizontalLayoutForPasswordRow = QtWidgets.QHBoxLayout()
        self.horizontalLayoutForPasswordRow.setObjectName("horizontalLayoutForPasswordRow")
        self.labelPassword = QtWidgets.QLabel(parent=self.authWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.horizontalLayoutForPasswordRow.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.authWidget)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayoutForPasswordRow.addWidget(self.lineEditPassword)
        self.verticalLayout_2.addLayout(self.horizontalLayoutForPasswordRow)
        self.horizontalLayoutAuth.addWidget(self.authWidget)
        self.verticalLayout_3.addLayout(self.horizontalLayoutAuth)
        self.horizontalLayoutButtonEntry = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtonEntry.setObjectName("horizontalLayoutButtonEntry")
        self.pushButtonEntry = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonEntry.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButtonEntry.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonEntry.setObjectName("pushButtonEntry")
        self.horizontalLayoutButtonEntry.addWidget(self.pushButtonEntry)
        self.verticalLayout_3.addLayout(self.horizontalLayoutButtonEntry)
        self.verticalLayout_4.addWidget(self.widget)
        self.stackedWidget.addWidget(self.authPage)
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.appBarMainPageWidget = QtWidgets.QWidget(parent=self.mainPage)
        self.appBarMainPageWidget.setMaximumSize(QtCore.QSize(16777215, 112))
        self.appBarMainPageWidget.setStyleSheet("background-color: rgb(118, 227, 131)")
        self.appBarMainPageWidget.setObjectName("appBarMainPageWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.appBarMainPageWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logoMainPage = QtWidgets.QLabel(parent=self.appBarMainPageWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logoMainPage.sizePolicy().hasHeightForWidth())
        self.logoMainPage.setSizePolicy(sizePolicy)
        self.logoMainPage.setMaximumSize(QtCore.QSize(77, 102))
        self.logoMainPage.setText("")
        self.logoMainPage.setPixmap(QtGui.QPixmap("logo.png"))
        self.logoMainPage.setScaledContents(True)
        self.logoMainPage.setObjectName("logoMainPage")
        self.horizontalLayout_4.addWidget(self.logoMainPage)
        self.labelMainPageTitle = QtWidgets.QLabel(parent=self.appBarMainPageWidget)
        self.labelMainPageTitle.setMaximumSize(QtCore.QSize(16777215, 102))
        self.labelMainPageTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelMainPageTitle.setObjectName("labelMainPageTitle")
        self.horizontalLayout_4.addWidget(self.labelMainPageTitle)

        self.pushButtonLogOut = QtWidgets.QPushButton()
        self.pushButtonLogOut.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButtonLogOut.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")

        self.pushButtonUpdate = QtWidgets.QPushButton()
        self.pushButtonUpdate.setMaximumSize(QtCore.QSize(70, 50))
        self.pushButtonUpdate.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout_4.addWidget(self.pushButtonUpdate)
        self.horizontalLayout_4.addWidget(self.pushButtonLogOut)
        
        
        self.horizontalLayout_4.setContentsMargins(10, 5, 10, 5)

        self.verticalLayout_5.addWidget(self.appBarMainPageWidget)
        self.tabWidgetMainPage = QtWidgets.QTabWidget(parent=self.mainPage)
        self.tabWidgetMainPage.setStyleSheet("")
        self.tabWidgetMainPage.setObjectName("tabWidgetMainPage")
        self.tabSmeny = QtWidgets.QWidget()
        self.tabSmeny.setObjectName("tabSmeny")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabSmeny)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tableWidgetSmeny = QtWidgets.QTableWidget(parent=self.tabSmeny)
        self.tableWidgetSmeny.setStyleSheet("background-color: rgb(118, 227, 131)")
        self.tableWidgetSmeny.setObjectName("tableWidgetSmeny")
        self.tableWidgetSmeny.setColumnCount(0)
        self.tableWidgetSmeny.setRowCount(0)
        self.verticalLayout_7.addWidget(self.tableWidgetSmeny)
        self.horizontalAddSmena = QtWidgets.QHBoxLayout()
        self.horizontalAddSmena.setObjectName("horizontalAddSmena")
        self.pushButtonAddSmena = QtWidgets.QPushButton(parent=self.tabSmeny)
        self.pushButtonAddSmena.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonAddSmena.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonAddSmena.setObjectName("pushButtonAddSmena")
        self.horizontalAddSmena.addWidget(self.pushButtonAddSmena)
        self.verticalLayout_7.addLayout(self.horizontalAddSmena)
        self.tabWidgetMainPage.addTab(self.tabSmeny, "")
        self.tabOrders = QtWidgets.QWidget()
        self.tabOrders.setObjectName("tabOrders")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabOrders)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tableWidgetOrders = QtWidgets.QTableWidget(parent=self.tabOrders)
        self.tableWidgetOrders.setStyleSheet("background-color: rgb(118, 227, 131)")
        self.tableWidgetOrders.setObjectName("tableWidgetOrders")
        self.tableWidgetOrders.setColumnCount(0)
        self.tableWidgetOrders.setRowCount(0)
        self.verticalLayout_8.addWidget(self.tableWidgetOrders)
        self.horizontalLayoutChangeStatus = QtWidgets.QHBoxLayout()
        self.horizontalLayoutChangeStatus.setObjectName("horizontalLayoutChangeStatus")
        self.pushButtonChangeStatus = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonChangeStatus.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonChangeStatus.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonChangeStatus.setObjectName("pushButtonChangeStatus")
        self.horizontalLayoutChangeStatus.addWidget(self.pushButtonChangeStatus)
        self.verticalLayout_8.addLayout(self.horizontalLayoutChangeStatus)
        self.horizontalLayoutCreateOrder = QtWidgets.QHBoxLayout()
        self.horizontalLayoutCreateOrder.setObjectName("horizontalLayoutCreateOrder")
        self.pushButtonCreateOrder = QtWidgets.QPushButton(parent=self.tabOrders)
        self.pushButtonCreateOrder.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonCreateOrder.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonCreateOrder.setObjectName("pushButtonCreateOrder")
        self.horizontalLayoutCreateOrder.addWidget(self.pushButtonCreateOrder)
        self.verticalLayout_8.addLayout(self.horizontalLayoutCreateOrder)
        self.tabWidgetMainPage.addTab(self.tabOrders, "")
        self.tabEmployees = QtWidgets.QWidget()
        self.tabEmployees.setObjectName("tabEmployees")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabEmployees)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidgetEmployees = QtWidgets.QTableWidget(parent=self.tabEmployees)
        self.tableWidgetEmployees.setStyleSheet("background-color: rgb(118, 227, 131)")
        self.tableWidgetEmployees.setObjectName("tableWidgetEmployees")
        self.tableWidgetEmployees.setColumnCount(0)
        self.tableWidgetEmployees.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidgetEmployees)
        self.horizontalLayoutAddEmployee = QtWidgets.QHBoxLayout()
        self.horizontalLayoutAddEmployee.setObjectName("horizontalLayoutAddEmployee")
        self.pushButtonAddEmployee = QtWidgets.QPushButton(parent=self.tabEmployees)
        self.pushButtonAddEmployee.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonAddEmployee.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonAddEmployee.setObjectName("pushButtonAddEmployee")
        self.horizontalLayoutAddEmployee.addWidget(self.pushButtonAddEmployee)
        self.verticalLayout_6.addLayout(self.horizontalLayoutAddEmployee)
        self.horizontalLayoutDeleteEmployee = QtWidgets.QHBoxLayout()
        self.horizontalLayoutDeleteEmployee.setObjectName("horizontalLayoutDeleteEmployee")
        self.pushButtonDeleteEmployee = QtWidgets.QPushButton(parent=self.tabEmployees)
        self.pushButtonDeleteEmployee.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pushButtonDeleteEmployee.setStyleSheet("background-color: rgb(153, 102, 51)")
        self.pushButtonDeleteEmployee.setObjectName("pushButtonDeleteEmployee")
        self.horizontalLayoutDeleteEmployee.addWidget(self.pushButtonDeleteEmployee)
        self.verticalLayout_6.addLayout(self.horizontalLayoutDeleteEmployee)
        self.tabWidgetMainPage.addTab(self.tabEmployees, "")
        self.verticalLayout_5.addWidget(self.tabWidgetMainPage)
        self.stackedWidget.addWidget(self.mainPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.mainWidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidgetMainPage.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Сезон"))
        self.labelAuthTitle.setText(_translate("MainWindow", "Авторизация"))
        self.labelLogin.setText(_translate("MainWindow", "Логин"))
        self.labelPassword.setText(_translate("MainWindow", "Пароль"))
        self.pushButtonEntry.setText(_translate("MainWindow", "Войти"))
        self.labelMainPageTitle.setText(_translate("MainWindow", "Роль"))
        self.pushButtonAddSmena.setText(_translate("MainWindow", "Добавить смену"))
        self.tabWidgetMainPage.setTabText(self.tabWidgetMainPage.indexOf(self.tabSmeny), _translate("MainWindow", "Смены"))
        self.pushButtonChangeStatus.setText(_translate("MainWindow", "Изменить статус"))
        self.pushButtonCreateOrder.setText(_translate("MainWindow", "Создать заказ"))
        self.tabWidgetMainPage.setTabText(self.tabWidgetMainPage.indexOf(self.tabOrders), _translate("MainWindow", "Заказы"))
        self.pushButtonAddEmployee.setText(_translate("MainWindow", "Добавить сотрудника"))
        self.pushButtonDeleteEmployee.setText(_translate("MainWindow", "Уволить сотрудника"))
        self.tabWidgetMainPage.setTabText(self.tabWidgetMainPage.indexOf(self.tabEmployees), _translate("MainWindow", "Сотрудники"))
        self.tableWidgetOrders.setWordWrap(True)
        self.tableWidgetEmployees.setWordWrap(True)
        self.tableWidgetSmeny.setWordWrap(True)
        self.pushButtonLogOut.setText(_translate("MainWindow", "Выйти"))
        self.pushButtonUpdate.setText(_translate("MainWindow", "Обновить"))
        
        


    def showErrorDialog(self, title, content):
        dlg = QtWidgets.QMessageBox()
        dlg.setWindowTitle(title)
        dlg.setText(content)
        dlg.setStandardButtons(QtWidgets.QMessageBox.StandardButton.Ok)
        dlg.exec()

    def fillOrderTableWidget(self, smenyWithOrders: List):
        self.tableWidgetOrders.setRowCount(0)
        self.tableWidgetOrders.setColumnCount(9)
        columnLables = ['Номер смены', 'Время смены', 'Номер заказа', 'Номер стола', 'Количество клиентов', 'Время заказа', 'Напитки', 'Блюда', 'Статус']
        self.tableWidgetOrders.setHorizontalHeaderLabels(columnLables)
        busyRowsCount = 0
        for index in range(len(smenyWithOrders)):
            
            current_smena = smenyWithOrders[index]
            count_employees = len(current_smena[2])
            self.tableWidgetOrders.setRowCount(self.tableWidgetOrders.rowCount() + count_employees)
            self.tableWidgetOrders.setItem(busyRowsCount + index, 0, QtWidgets.QTableWidgetItem(str(current_smena[0])))
            self.tableWidgetOrders.setItem(busyRowsCount + index, 1, QtWidgets.QTableWidgetItem(current_smena[1].strftime("%Y-%m-%d %H:%M:%S")))
            
            for i in range(count_employees):
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 2, QtWidgets.QTableWidgetItem(str(current_smena[2][i])))
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 3, QtWidgets.QTableWidgetItem(str(current_smena[3][i])))
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 4, QtWidgets.QTableWidgetItem(str(current_smena[4][i])))
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 5, QtWidgets.QTableWidgetItem(current_smena[5][i].strftime("%Y-%m-%d %H:%M:%S")))
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 6, QtWidgets.QTableWidgetItem(current_smena[6][i]))
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 7, QtWidgets.QTableWidgetItem(current_smena[7][i]))
                self.tableWidgetOrders.setItem(busyRowsCount + index + i, 8, QtWidgets.QTableWidgetItem(current_smena[8][i]))
            busyRowsCount += count_employees - 1

        self.tableWidgetOrders.setVerticalHeaderLabels(['' for _ in range(self.tableWidgetOrders.rowCount())])
        self.tableWidgetOrders.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidgetOrders.resizeRowsToContents()

    def fillSmenaTableWidget(self, smenyWithEmployees: List):
        self.tableWidgetSmeny.setRowCount(0)
        self.tableWidgetSmeny.setColumnCount(6)
        columnLables = ['Номер смены', 'Время смены', 'Номер сотрудника', 'Имя сотрудника', 'Фамилия сотрудника', 'Роль сотрудника']
        self.tableWidgetSmeny.setHorizontalHeaderLabels(columnLables)
        busyRowsCount = 0
        for index in range(len(smenyWithEmployees)):
            
            current_smena = smenyWithEmployees[index]
            count_employees = len(current_smena[2])
            self.tableWidgetSmeny.setRowCount(self.tableWidgetSmeny.rowCount() + count_employees)
            self.tableWidgetSmeny.setItem(busyRowsCount + index, 0, QtWidgets.QTableWidgetItem(str(current_smena[0])))
            self.tableWidgetSmeny.setItem(busyRowsCount + index, 1, QtWidgets.QTableWidgetItem(current_smena[1].strftime("%Y-%m-%d %H:%M:%S")))
            
            for i in range(count_employees):
                self.tableWidgetSmeny.setItem(busyRowsCount + index + i, 2, QtWidgets.QTableWidgetItem(str(current_smena[2][i])))
                self.tableWidgetSmeny.setItem(busyRowsCount + index + i, 3, QtWidgets.QTableWidgetItem(current_smena[3][i]))
                self.tableWidgetSmeny.setItem(busyRowsCount + index + i, 4, QtWidgets.QTableWidgetItem(current_smena[4][i]))
                self.tableWidgetSmeny.setItem(busyRowsCount + index + i, 5, QtWidgets.QTableWidgetItem(current_smena[5][i]))

            busyRowsCount += count_employees - 1

        self.tableWidgetSmeny.setVerticalHeaderLabels(['' for _ in range(self.tableWidgetSmeny.rowCount())])
        self.tableWidgetSmeny.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidgetSmeny.resizeRowsToContents()
        
        

    def showInputDialogAddSmena(self, employees):
        dialog = InputDialogAddSmena()
        dialog.fillEmployeesTable(employees)
        return dialog
    
    def showInputDialogAddEmployee(self):
        dialog = InputDialogAddEmployee()
        return dialog
    
    def showInputDialogAddOrder(self):
        dialog = InputDialogAddOrder()
        return dialog
    

    def fillEmployeesTableWidget(self, employees: List):
        count_employees = len(employees)
        self.tableWidgetEmployees.setColumnCount(4)
        self.tableWidgetEmployees.setRowCount(count_employees)

        for i in range(count_employees):
            for j in range(4):
                self.tableWidgetEmployees.setItem(i, j, QtWidgets.QTableWidgetItem(str(employees[i][j])))
        self.tableWidgetEmployees.setVerticalHeaderLabels(['' for _ in range(self.tableWidgetEmployees.rowCount())])
        columnLables = ['Номер сотрудника', 'Имя сотрудника', 'Фамилия сотрудника', 'Роль сотрудника']
        self.tableWidgetEmployees.setHorizontalHeaderLabels(columnLables)
        self.tableWidgetEmployees.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.tableWidgetEmployees.resizeRowsToContents()
        

class InputDialogAddSmena(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle('Создание смены')

        self.employeesTable = QtWidgets.QTableWidget()
        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(self.employeesTable)

        self.buttonOk = QtWidgets.QPushButton('Oк', self)
        self.layout.addWidget(self.buttonOk)

        self.buttonOk.clicked.connect(self.accept)

        self.buttonCancel = QtWidgets.QPushButton('Отмена', self)
        self.layout.addWidget(self.buttonCancel)

        self.buttonCancel.clicked.connect(self.reject)
        self.setLayout(self.layout)


    def fillEmployeesTable(self, employees: List):
        self.resize(550, 400)
        count_employees = len(employees)
        self.employeesTable.setColumnCount(4)
        self.employeesTable.setRowCount(count_employees)

        for i in range(count_employees):
            for j in range(4):
                self.employeesTable.setItem(i, j, QtWidgets.QTableWidgetItem(str(employees[i][j])))
        self.employeesTable.setVerticalHeaderLabels(['' for _ in range(self.employeesTable.rowCount())])
        columnLables = ['Номер сотрудника', 'Имя сотрудника', 'Фамилия сотрудника', 'Роль сотрудника']
        self.employeesTable.setHorizontalHeaderLabels(columnLables)
        self.employeesTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.Stretch)
        self.employeesTable.resizeRowsToContents()

        
class InputDialogAddEmployee(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle('Создание Сотрудника')

        self.lineEditName = QtWidgets.QLineEdit()
        self.lineEditSecondName = QtWidgets.QLineEdit()
        self.comboBoxRole = QtWidgets.QComboBox()
        self.comboBoxRole.addItem('Администратор', 1)
        self.comboBoxRole.addItem('Официант', 2)
        self.comboBoxRole.addItem('Повар', 3)

        self.lineEditLogin = QtWidgets.QLineEdit()

        self.lineEditPassword = QtWidgets.QLineEdit()
        


        self.layout = QtWidgets.QFormLayout()
        self.layout.addRow(
            'Имя',
            self.lineEditName,
        )
        self.layout.addRow(
            'Фамилия',
            self.lineEditSecondName,
        )
        self.layout.addRow(
            'Логин',
            self.lineEditLogin,
        )
        self.layout.addRow(
            'Пароль',
            self.lineEditPassword,
        )
        self.layout.addRow(
            'Роль',
            self.comboBoxRole,
        )
        self.buttonOk = QtWidgets.QPushButton('Oк', self)
        self.layout.addWidget(self.buttonOk)

        self.buttonOk.clicked.connect(self.accept)

        self.buttonCancel = QtWidgets.QPushButton('Отмена', self)
        self.layout.addWidget(self.buttonCancel)

        self.buttonCancel.clicked.connect(self.reject)
        self.setLayout(self.layout)
        
class InputDialogAddOrder(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle('Создание Заказа')

        self.lineEditTable = QtWidgets.QLineEdit()
        self.lineEditTable.setValidator(QtGui.QIntValidator())
        self.lineEditCountClient = QtWidgets.QLineEdit()
        self.lineEditCountClient.setValidator(QtGui.QIntValidator())
        
        self.lineEditDrinks = QtWidgets.QLineEdit()
        self.lineEditDishes = QtWidgets.QLineEdit()

        self.layout = QtWidgets.QFormLayout()
        self.layout.addRow(
            'Столик',
            self.lineEditTable,
        )
        self.layout.addRow(
            'Количество клиентов',
            self.lineEditCountClient,
        )
    
        self.layout.addRow(
            'Напитки',
            self.lineEditDrinks,
        )
        self.layout.addRow(
            'Блюда',
            self.lineEditDishes,
        )
        self.buttonOk = QtWidgets.QPushButton('Oк', self)
        self.layout.addWidget(self.buttonOk)

        self.buttonOk.clicked.connect(self.accept)

        self.buttonCancel = QtWidgets.QPushButton('Отмена', self)
        self.layout.addWidget(self.buttonCancel)

        self.buttonCancel.clicked.connect(self.reject)
        self.setLayout(self.layout)

    

    